# Generated by Django 5.1.2 on 2024-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Excerpts',
            field=models.CharField(max_length=200),
        ),
    ]
